; PlatformIO Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @ ^6.7.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.partitions = custom_16Mb.csv
lib_deps = 
    mquickjs
    bblanchon/ArduinoJson@^6.21.3
    Wire
    FS
    SPI
    SD@^2.0.0

[env:lilygo-t-embed-cc1101]
board = esp32-s3-devkitc-1
build_flags = 
    -DARDUINO_LILYGO_T_EMBED_CC1101
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_LITTLEFS_FOR_IDF_3_2
    -DUSE_SPI_SD
    -DSD_SS_PIN=5
    -DTOUCH_CS=-1
    -DHAS_BRUCETHEME

lib_ignore = 
    SD(esp32)
    SD(esp8266)
    SDFS
    SdFat
    SD_MMC
    Ethernet
    WiFi

platform_packages = 
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/2.0.14/esp32-2.0.14.zip

[env:lilygo-t-embed-cc1101-lite]
extends = env:lilygo-t-embed-cc1101
build_flags = 
    ${env:lilygo-t-embed-cc1101.build_flags}
    -DLITE_VERSION

[env:lilygo-t-embed-cc1101-debug]
extends = env:lilygo-t-embed-cc1101
build_type = debug
build_flags = 
    ${env:lilygo-t-embed-cc1101.build_flags}
    -DDEBUG
    -DDEBUG_ESP_PORT=Serial

[env:lilygo-t-embed-cc1101-release]
extends = env:lilygo-t-embed-cc1101
build_type = release
build_flags = 
    ${env:lilygo-t-embed-cc1101.build_flags}
    -DRELEASE
    -Os
