[platformio]
platform = espressif32 @ ^6.7.0
lib_deps = 
    mquickjs
    bblanchon/ArduinoJson@^6.21.3

[env]
platform = espressif32 @ ^6.7.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.partitions = custom_16Mb.csv
lib_deps = 
    ${platformio.lib_deps}

[env:lilygo-t-embed-cc1101]
board = esp32-s3-devkitc-1
build_flags = 
    -DARDUINO_LILYGO_T_EMBED_CC1101
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_LITTLEFS_FOR_IDF_3_2
    -DTFT_eSPI=1
    -DUSE_SPI_SD
    -DSD_SS_PIN=5
    -DTOUCH_CS=-1

lib_ignore = 
    SD(esp32)
    SD(esp8266)
    SDFS
    SdFat
    SD_MMC
    Ethernet
    WiFi
