[env:lilygo-t-embed-cc1101]
board = lilygo-t-embed-cc1101
platform = espressif32
framework = arduino
board_build.partitions = custom_16Mb.csv
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DDEVICE_NAME="Lilygo T-Embed CC1101"
    ; САМОЕ ВАЖНОЕ: Явно определяем что нет тачскрина
    -DTOUCH_CS=-1
    -DHAS_TOUCH=0
    -DTOUCH_IRQ=-1
    ; Дисплей
    -DDISPLAY_WIDTH=170
    -DDISPLAY_HEIGHT=320
    -DTFT_CS=41
    -DTFT_DC=16
    -DTFT_RST=40
    -DTFT_BL=21
lib_deps =
    lewisxhe/XPowersLib @^0.3.3
    mathertel/RotaryEncoder @1.5.3
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
