name: Build Bruce for T-Embed CC1101

on:
  push:
    branches: [ "t-embed-custom-mod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install PlatformIO
      run: pip install platformio
      
    - name: Build
      run: pio run -e lilygo-t-embed-cc1101
      
    - name: Upload
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: bruce-firmware
        path: .pio/build/lilygo-t-embed-cc1101/firmware.bin
