name: CI

on:
  push:
    branches: [ fix-compilation-errors ]
  pull_request:
    branches: [ t-embed-custom-mod ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PlatformIO
      run: pip install platformio
      
    - name: Install Platform
      run: pio platform install espressif32@6.5.0
      
    - name: Install Libraries
      run: pio lib install ArduinoJson@6.21.3
      
    - name: Build
      run: pio run -e lilygo-t-embed-cc1101
